#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 145
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 1
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define PRODUCTION_ID_COUNT 11

enum {
  aux_sym_code_token1 = 1,
  sym_content = 2,
  anon_sym_LBRACE_LBRACE = 3,
  anon_sym_EQ = 4,
  anon_sym_RBRACE_RBRACE = 5,
  anon_sym_html = 6,
  anon_sym_BANG = 7,
  anon_sym_var = 8,
  anon_sym_ = 9,
  aux_sym_var_directive_token1 = 10,
  anon_sym_EQ2 = 11,
  anon_sym_if = 12,
  anon_sym_LBRACE_LBRACE_SLASH = 13,
  anon_sym_RBRACE_RBRACE2 = 14,
  anon_sym_else = 15,
  anon_sym_each = 16,
  anon_sym_LPAREN = 17,
  aux_sym_each_directive_token1 = 18,
  anon_sym_COMMA = 19,
  aux_sym_each_directive_token2 = 20,
  anon_sym_RPAREN = 21,
  anon_sym_partial = 22,
  aux_sym_partial_directive_token1 = 23,
  sym_template = 24,
  sym__node = 25,
  sym_code = 26,
  sym_output_directive = 27,
  sym_html_directive = 28,
  sym_comment_directive = 29,
  sym_var_directive = 30,
  sym_if_directive = 31,
  sym_else_directive = 32,
  sym_each_directive = 33,
  sym_partial_directive = 34,
  aux_sym_template_repeat1 = 35,
  aux_sym_code_repeat1 = 36,
  alias_sym_comment = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_code_token1] = "code_token1",
  [sym_content] = "content",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_html] = "html",
  [anon_sym_BANG] = "!",
  [anon_sym_var] = "var",
  [anon_sym_] = " ",
  [aux_sym_var_directive_token1] = "code",
  [anon_sym_EQ2] = " = ",
  [anon_sym_if] = "if",
  [anon_sym_LBRACE_LBRACE_SLASH] = "{{/",
  [anon_sym_RBRACE_RBRACE2] = "}}",
  [anon_sym_else] = "else",
  [anon_sym_each] = "each",
  [anon_sym_LPAREN] = "(",
  [aux_sym_each_directive_token1] = "each_directive_token1",
  [anon_sym_COMMA] = ",",
  [aux_sym_each_directive_token2] = "each_directive_token2",
  [anon_sym_RPAREN] = ")",
  [anon_sym_partial] = "partial",
  [aux_sym_partial_directive_token1] = "code",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_code] = "code",
  [sym_output_directive] = "output_directive",
  [sym_html_directive] = "html_directive",
  [sym_comment_directive] = "comment_directive",
  [sym_var_directive] = "var_directive",
  [sym_if_directive] = "if_directive",
  [sym_else_directive] = "else_directive",
  [sym_each_directive] = "each_directive",
  [sym_partial_directive] = "partial_directive",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [alias_sym_comment] = "comment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [sym_content] = sym_content,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_html] = anon_sym_html,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_] = anon_sym_,
  [aux_sym_var_directive_token1] = sym_code,
  [anon_sym_EQ2] = anon_sym_EQ2,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_LBRACE_LBRACE_SLASH] = anon_sym_LBRACE_LBRACE_SLASH,
  [anon_sym_RBRACE_RBRACE2] = anon_sym_RBRACE_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_each_directive_token1] = aux_sym_each_directive_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_each_directive_token2] = aux_sym_each_directive_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_partial] = anon_sym_partial,
  [aux_sym_partial_directive_token1] = sym_code,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_code] = sym_code,
  [sym_output_directive] = sym_output_directive,
  [sym_html_directive] = sym_html_directive,
  [sym_comment_directive] = sym_comment_directive,
  [sym_var_directive] = sym_var_directive,
  [sym_if_directive] = sym_if_directive,
  [sym_else_directive] = sym_else_directive,
  [sym_each_directive] = sym_each_directive,
  [sym_partial_directive] = sym_partial_directive,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [alias_sym_comment] = alias_sym_comment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_html] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_var_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_partial] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_partial_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_html_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_var_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_else_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_each_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_comment] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_alternative = 1,
  field_bindings = 2,
  field_condition = 3,
  field_consequence = 4,
  field_path = 5,
  field_var_name = 6,
  field_var_value = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_bindings] = "bindings",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_path] = "path",
  [field_var_name] = "var_name",
  [field_var_value] = "var_value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 2},
  [8] = {.index = 9, .length = 2},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_var_name, 3},
    {field_var_value, 5},
  [2] =
    {field_condition, 2},
  [3] =
    {field_bindings, 3},
    {field_path, 5},
  [5] =
    {field_alternative, 3},
  [6] =
    {field_consequence, 3},
  [7] =
    {field_alternative, 4},
    {field_condition, 2},
  [9] =
    {field_condition, 2},
    {field_consequence, 4},
  [11] =
    {field_alternative, 4},
    {field_consequence, 3},
  [13] =
    {field_alternative, 5},
    {field_condition, 2},
    {field_consequence, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_comment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_code, 2,
    sym_code,
    alias_sym_comment,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 5,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 12,
  [15] = 15,
  [16] = 15,
  [17] = 10,
  [18] = 13,
  [19] = 19,
  [20] = 11,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 30,
  [31] = 27,
  [32] = 30,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 45,
  [48] = 48,
  [49] = 48,
  [50] = 44,
  [51] = 51,
  [52] = 46,
  [53] = 53,
  [54] = 54,
  [55] = 43,
  [56] = 56,
  [57] = 51,
  [58] = 35,
  [59] = 42,
  [60] = 41,
  [61] = 38,
  [62] = 34,
  [63] = 33,
  [64] = 36,
  [65] = 37,
  [66] = 53,
  [67] = 39,
  [68] = 68,
  [69] = 56,
  [70] = 40,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 72,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 94,
  [104] = 93,
  [105] = 88,
  [106] = 86,
  [107] = 85,
  [108] = 108,
  [109] = 71,
  [110] = 76,
  [111] = 79,
  [112] = 112,
  [113] = 113,
  [114] = 97,
  [115] = 115,
  [116] = 92,
  [117] = 91,
  [118] = 84,
  [119] = 75,
  [120] = 73,
  [121] = 77,
  [122] = 112,
  [123] = 123,
  [124] = 98,
  [125] = 96,
  [126] = 126,
  [127] = 90,
  [128] = 102,
  [129] = 101,
  [130] = 100,
  [131] = 131,
  [132] = 126,
  [133] = 123,
  [134] = 113,
  [135] = 135,
  [136] = 81,
  [137] = 137,
  [138] = 137,
  [139] = 131,
  [140] = 89,
  [141] = 95,
  [142] = 99,
  [143] = 115,
  [144] = 135,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '!') ADVANCE(41);
      if (lookahead == '(') ADVANCE(52);
      if (lookahead == ')') ADVANCE(56);
      if (lookahead == ',') ADVANCE(54);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(6);
      if (lookahead == 'h') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(7);
      if (lookahead == 'v') ADVANCE(8);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      END_STATE();
    case 1:
      if (lookahead == ' ') ADVANCE(46);
      END_STATE();
    case 2:
      if (lookahead == ' ') ADVANCE(5);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 3:
      if (lookahead == ' ') ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '(') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(10);
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(50);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(51);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(9);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(57);
      END_STATE();
    case 17:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 23:
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == '}') ADVANCE(49);
      END_STATE();
    case 25:
      if (lookahead == '}') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(55);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(53);
      END_STATE();
    case 29:
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(36);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '}') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '}') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '}') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_content);
      if (lookahead == '{') ADVANCE(29);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_html);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '=') ADVANCE(1);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_var_directive_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_EQ2);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_SLASH);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE2);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_each_directive_token1);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_each_directive_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_partial);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_partial_directive_token1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(58);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 30},
  [2] = {.lex_state = 30},
  [3] = {.lex_state = 30},
  [4] = {.lex_state = 30},
  [5] = {.lex_state = 30},
  [6] = {.lex_state = 30},
  [7] = {.lex_state = 30},
  [8] = {.lex_state = 30},
  [9] = {.lex_state = 30},
  [10] = {.lex_state = 30},
  [11] = {.lex_state = 30},
  [12] = {.lex_state = 30},
  [13] = {.lex_state = 30},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 30},
  [18] = {.lex_state = 30},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 30},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 26},
  [25] = {.lex_state = 26},
  [26] = {.lex_state = 26},
  [27] = {.lex_state = 26},
  [28] = {.lex_state = 26},
  [29] = {.lex_state = 26},
  [30] = {.lex_state = 26},
  [31] = {.lex_state = 26},
  [32] = {.lex_state = 26},
  [33] = {.lex_state = 30},
  [34] = {.lex_state = 30},
  [35] = {.lex_state = 26},
  [36] = {.lex_state = 30},
  [37] = {.lex_state = 30},
  [38] = {.lex_state = 26},
  [39] = {.lex_state = 30},
  [40] = {.lex_state = 26},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 30},
  [43] = {.lex_state = 30},
  [44] = {.lex_state = 30},
  [45] = {.lex_state = 30},
  [46] = {.lex_state = 30},
  [47] = {.lex_state = 30},
  [48] = {.lex_state = 30},
  [49] = {.lex_state = 30},
  [50] = {.lex_state = 30},
  [51] = {.lex_state = 30},
  [52] = {.lex_state = 30},
  [53] = {.lex_state = 30},
  [54] = {.lex_state = 26},
  [55] = {.lex_state = 30},
  [56] = {.lex_state = 30},
  [57] = {.lex_state = 30},
  [58] = {.lex_state = 26},
  [59] = {.lex_state = 30},
  [60] = {.lex_state = 30},
  [61] = {.lex_state = 26},
  [62] = {.lex_state = 30},
  [63] = {.lex_state = 30},
  [64] = {.lex_state = 30},
  [65] = {.lex_state = 30},
  [66] = {.lex_state = 30},
  [67] = {.lex_state = 30},
  [68] = {.lex_state = 26},
  [69] = {.lex_state = 30},
  [70] = {.lex_state = 26},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 2},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 26},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 26},
  [88] = {.lex_state = 26},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 26},
  [95] = {.lex_state = 27},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 26},
  [101] = {.lex_state = 26},
  [102] = {.lex_state = 26},
  [103] = {.lex_state = 26},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 26},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 58},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 28},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 26},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 26},
  [129] = {.lex_state = 26},
  [130] = {.lex_state = 26},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 26},
  [134] = {.lex_state = 58},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 26},
  [137] = {.lex_state = 3},
  [138] = {.lex_state = 3},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 27},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 28},
  [144] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_html] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_] = ACTIONS(1),
    [anon_sym_EQ2] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_SLASH] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE2] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_partial] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(74),
    [sym__node] = STATE(19),
    [sym_output_directive] = STATE(19),
    [sym_html_directive] = STATE(19),
    [sym_comment_directive] = STATE(19),
    [sym_var_directive] = STATE(19),
    [sym_if_directive] = STATE(19),
    [sym_each_directive] = STATE(19),
    [sym_partial_directive] = STATE(19),
    [aux_sym_template_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_content] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(9), 1,
      sym_content,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(83), 1,
      sym_else_directive,
    STATE(3), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [24] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(80), 1,
      sym_else_directive,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [48] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(19), 1,
      sym_content,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(78), 1,
      sym_else_directive,
    STATE(9), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [72] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(23), 1,
      sym_content,
    ACTIONS(25), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(125), 1,
      sym_else_directive,
    STATE(8), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [96] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(27), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(90), 1,
      sym_else_directive,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [120] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(29), 1,
      sym_content,
    ACTIONS(31), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(96), 1,
      sym_else_directive,
    STATE(6), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [144] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(33), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(127), 1,
      sym_else_directive,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [168] = 5,
    ACTIONS(11), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(108), 1,
      sym_else_directive,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [192] = 4,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      sym_content,
    ACTIONS(42), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(10), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [213] = 4,
    ACTIONS(45), 1,
      sym_content,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(14), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [234] = 4,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(51), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [255] = 4,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(49), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [276] = 4,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(53), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [297] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(55), 1,
      sym_content,
    ACTIONS(57), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(18), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [318] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(59), 1,
      sym_content,
    ACTIONS(61), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(13), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [339] = 4,
    ACTIONS(37), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    ACTIONS(63), 1,
      sym_content,
    ACTIONS(66), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [360] = 4,
    ACTIONS(15), 1,
      sym_content,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    STATE(17), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [381] = 4,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(71), 1,
      ts_builtin_sym_end,
    ACTIONS(73), 1,
      sym_content,
    STATE(10), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [402] = 4,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(69), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
    ACTIONS(75), 1,
      sym_content,
    STATE(12), 9,
      sym__node,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_var_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
  [423] = 8,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(79), 1,
      anon_sym_html,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_var,
    ACTIONS(85), 1,
      anon_sym_if,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
  [448] = 7,
    ACTIONS(93), 1,
      anon_sym_EQ,
    ACTIONS(95), 1,
      anon_sym_html,
    ACTIONS(97), 1,
      anon_sym_BANG,
    ACTIONS(99), 1,
      anon_sym_var,
    ACTIONS(101), 1,
      anon_sym_if,
    ACTIONS(103), 1,
      anon_sym_each,
    ACTIONS(105), 1,
      anon_sym_partial,
  [470] = 7,
    ACTIONS(77), 1,
      anon_sym_EQ,
    ACTIONS(79), 1,
      anon_sym_html,
    ACTIONS(81), 1,
      anon_sym_BANG,
    ACTIONS(83), 1,
      anon_sym_var,
    ACTIONS(85), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
  [492] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(109), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(136), 1,
      sym_code,
  [505] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(111), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(81), 1,
      sym_code,
  [518] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(113), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(87), 1,
      sym_code,
  [531] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(115), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(130), 1,
      sym_code,
  [544] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(117), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(102), 1,
      sym_code,
  [557] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(119), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(128), 1,
      sym_code,
  [570] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(121), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(101), 1,
      sym_code,
  [583] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(123), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(100), 1,
      sym_code,
  [596] = 4,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    ACTIONS(125), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(129), 1,
      sym_code,
  [609] = 2,
    ACTIONS(129), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(127), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [617] = 2,
    ACTIONS(133), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(131), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [625] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(94), 1,
      sym_code,
  [635] = 2,
    ACTIONS(137), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(135), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [643] = 2,
    ACTIONS(141), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(139), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [651] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(88), 1,
      sym_code,
  [661] = 2,
    ACTIONS(145), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(143), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [669] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(133), 1,
      sym_code,
  [679] = 2,
    ACTIONS(149), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(147), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [687] = 2,
    ACTIONS(153), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(151), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [695] = 2,
    ACTIONS(157), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(155), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [703] = 2,
    ACTIONS(161), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(159), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [711] = 2,
    ACTIONS(165), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(163), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [719] = 2,
    ACTIONS(169), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(167), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [727] = 1,
    ACTIONS(163), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [733] = 1,
    ACTIONS(171), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [739] = 2,
    ACTIONS(173), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(171), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [747] = 1,
    ACTIONS(159), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [753] = 2,
    ACTIONS(177), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(175), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [761] = 1,
    ACTIONS(167), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [767] = 2,
    ACTIONS(181), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(179), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [775] = 3,
    ACTIONS(183), 1,
      aux_sym_code_token1,
    ACTIONS(186), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(54), 1,
      aux_sym_code_repeat1,
  [785] = 1,
    ACTIONS(155), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [791] = 2,
    ACTIONS(190), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(188), 2,
      sym_content,
      anon_sym_LBRACE_LBRACE_SLASH,
  [799] = 1,
    ACTIONS(175), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [805] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(103), 1,
      sym_code,
  [815] = 1,
    ACTIONS(151), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [821] = 1,
    ACTIONS(147), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [827] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(105), 1,
      sym_code,
  [837] = 1,
    ACTIONS(131), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [843] = 1,
    ACTIONS(127), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [849] = 1,
    ACTIONS(135), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [855] = 1,
    ACTIONS(139), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [861] = 1,
    ACTIONS(179), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [867] = 1,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [873] = 3,
    ACTIONS(192), 1,
      aux_sym_code_token1,
    ACTIONS(194), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(54), 1,
      aux_sym_code_repeat1,
  [883] = 1,
    ACTIONS(188), 3,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE,
  [889] = 3,
    ACTIONS(107), 1,
      aux_sym_code_token1,
    STATE(68), 1,
      aux_sym_code_repeat1,
    STATE(123), 1,
      sym_code,
  [899] = 1,
    ACTIONS(196), 1,
      anon_sym_RBRACE_RBRACE2,
  [903] = 1,
    ACTIONS(198), 1,
      anon_sym_RBRACE_RBRACE2,
  [907] = 1,
    ACTIONS(200), 1,
      anon_sym_each,
  [911] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [915] = 1,
    ACTIONS(204), 1,
      anon_sym_each,
  [919] = 1,
    ACTIONS(206), 1,
      anon_sym_RBRACE_RBRACE2,
  [923] = 1,
    ACTIONS(208), 1,
      anon_sym_each,
  [927] = 1,
    ACTIONS(210), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [931] = 1,
    ACTIONS(212), 1,
      anon_sym_RBRACE_RBRACE2,
  [935] = 1,
    ACTIONS(214), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [939] = 1,
    ACTIONS(216), 1,
      anon_sym_RBRACE_RBRACE,
  [943] = 1,
    ACTIONS(218), 1,
      anon_sym_RBRACE_RBRACE2,
  [947] = 1,
    ACTIONS(220), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [951] = 1,
    ACTIONS(222), 1,
      anon_sym_if,
  [955] = 1,
    ACTIONS(224), 1,
      anon_sym_RBRACE_RBRACE2,
  [959] = 1,
    ACTIONS(226), 1,
      anon_sym_RBRACE_RBRACE2,
  [963] = 1,
    ACTIONS(228), 1,
      anon_sym_RBRACE_RBRACE,
  [967] = 1,
    ACTIONS(230), 1,
      anon_sym_RBRACE_RBRACE,
  [971] = 1,
    ACTIONS(232), 1,
      anon_sym_RPAREN,
  [975] = 1,
    ACTIONS(234), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [979] = 1,
    ACTIONS(236), 1,
      anon_sym_if,
  [983] = 1,
    ACTIONS(238), 1,
      anon_sym_if,
  [987] = 1,
    ACTIONS(240), 1,
      anon_sym_RBRACE_RBRACE2,
  [991] = 1,
    ACTIONS(242), 1,
      anon_sym_RBRACE_RBRACE,
  [995] = 1,
    ACTIONS(244), 1,
      aux_sym_each_directive_token2,
  [999] = 1,
    ACTIONS(246), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [1003] = 1,
    ACTIONS(248), 1,
      anon_sym_if,
  [1007] = 1,
    ACTIONS(250), 1,
      anon_sym_RPAREN,
  [1011] = 1,
    ACTIONS(252), 1,
      anon_sym_COMMA,
  [1015] = 1,
    ACTIONS(254), 1,
      anon_sym_RBRACE_RBRACE,
  [1019] = 1,
    ACTIONS(256), 1,
      anon_sym_RBRACE_RBRACE,
  [1023] = 1,
    ACTIONS(258), 1,
      anon_sym_RBRACE_RBRACE,
  [1027] = 1,
    ACTIONS(260), 1,
      anon_sym_RBRACE_RBRACE,
  [1031] = 1,
    ACTIONS(262), 1,
      anon_sym_RBRACE_RBRACE2,
  [1035] = 1,
    ACTIONS(264), 1,
      anon_sym_RBRACE_RBRACE,
  [1039] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE_RBRACE2,
  [1043] = 1,
    ACTIONS(268), 1,
      anon_sym_RBRACE_RBRACE2,
  [1047] = 1,
    ACTIONS(270), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [1051] = 1,
    ACTIONS(272), 1,
      anon_sym_RBRACE_RBRACE2,
  [1055] = 1,
    ACTIONS(274), 1,
      anon_sym_RBRACE_RBRACE2,
  [1059] = 1,
    ACTIONS(276), 1,
      anon_sym_RBRACE_RBRACE2,
  [1063] = 1,
    ACTIONS(278), 1,
      anon_sym_EQ2,
  [1067] = 1,
    ACTIONS(280), 1,
      aux_sym_partial_directive_token1,
  [1071] = 1,
    ACTIONS(282), 1,
      anon_sym_if,
  [1075] = 1,
    ACTIONS(284), 1,
      aux_sym_each_directive_token1,
  [1079] = 1,
    ACTIONS(286), 1,
      anon_sym_if,
  [1083] = 1,
    ACTIONS(288), 1,
      anon_sym_if,
  [1087] = 1,
    ACTIONS(290), 1,
      anon_sym_if,
  [1091] = 1,
    ACTIONS(292), 1,
      anon_sym_each,
  [1095] = 1,
    ACTIONS(294), 1,
      anon_sym_each,
  [1099] = 1,
    ACTIONS(296), 1,
      anon_sym_each,
  [1103] = 1,
    ACTIONS(298), 1,
      anon_sym_EQ2,
  [1107] = 1,
    ACTIONS(300), 1,
      anon_sym_RBRACE_RBRACE,
  [1111] = 1,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
  [1115] = 1,
    ACTIONS(304), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [1119] = 1,
    ACTIONS(306), 1,
      aux_sym_var_directive_token1,
  [1123] = 1,
    ACTIONS(308), 1,
      anon_sym_LBRACE_LBRACE_SLASH,
  [1127] = 1,
    ACTIONS(310), 1,
      anon_sym_RBRACE_RBRACE,
  [1131] = 1,
    ACTIONS(312), 1,
      anon_sym_RBRACE_RBRACE,
  [1135] = 1,
    ACTIONS(314), 1,
      anon_sym_RBRACE_RBRACE,
  [1139] = 1,
    ACTIONS(316), 1,
      anon_sym_LPAREN,
  [1143] = 1,
    ACTIONS(318), 1,
      aux_sym_var_directive_token1,
  [1147] = 1,
    ACTIONS(320), 1,
      anon_sym_RBRACE_RBRACE,
  [1151] = 1,
    ACTIONS(322), 1,
      aux_sym_partial_directive_token1,
  [1155] = 1,
    ACTIONS(324), 1,
      anon_sym_LPAREN,
  [1159] = 1,
    ACTIONS(326), 1,
      anon_sym_RBRACE_RBRACE,
  [1163] = 1,
    ACTIONS(328), 1,
      anon_sym_,
  [1167] = 1,
    ACTIONS(330), 1,
      anon_sym_,
  [1171] = 1,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
  [1175] = 1,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
  [1179] = 1,
    ACTIONS(336), 1,
      aux_sym_each_directive_token2,
  [1183] = 1,
    ACTIONS(338), 1,
      anon_sym_COMMA,
  [1187] = 1,
    ACTIONS(340), 1,
      aux_sym_each_directive_token1,
  [1191] = 1,
    ACTIONS(342), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 24,
  [SMALL_STATE(4)] = 48,
  [SMALL_STATE(5)] = 72,
  [SMALL_STATE(6)] = 96,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 144,
  [SMALL_STATE(9)] = 168,
  [SMALL_STATE(10)] = 192,
  [SMALL_STATE(11)] = 213,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 255,
  [SMALL_STATE(14)] = 276,
  [SMALL_STATE(15)] = 297,
  [SMALL_STATE(16)] = 318,
  [SMALL_STATE(17)] = 339,
  [SMALL_STATE(18)] = 360,
  [SMALL_STATE(19)] = 381,
  [SMALL_STATE(20)] = 402,
  [SMALL_STATE(21)] = 423,
  [SMALL_STATE(22)] = 448,
  [SMALL_STATE(23)] = 470,
  [SMALL_STATE(24)] = 492,
  [SMALL_STATE(25)] = 505,
  [SMALL_STATE(26)] = 518,
  [SMALL_STATE(27)] = 531,
  [SMALL_STATE(28)] = 544,
  [SMALL_STATE(29)] = 557,
  [SMALL_STATE(30)] = 570,
  [SMALL_STATE(31)] = 583,
  [SMALL_STATE(32)] = 596,
  [SMALL_STATE(33)] = 609,
  [SMALL_STATE(34)] = 617,
  [SMALL_STATE(35)] = 625,
  [SMALL_STATE(36)] = 635,
  [SMALL_STATE(37)] = 643,
  [SMALL_STATE(38)] = 651,
  [SMALL_STATE(39)] = 661,
  [SMALL_STATE(40)] = 669,
  [SMALL_STATE(41)] = 679,
  [SMALL_STATE(42)] = 687,
  [SMALL_STATE(43)] = 695,
  [SMALL_STATE(44)] = 703,
  [SMALL_STATE(45)] = 711,
  [SMALL_STATE(46)] = 719,
  [SMALL_STATE(47)] = 727,
  [SMALL_STATE(48)] = 733,
  [SMALL_STATE(49)] = 739,
  [SMALL_STATE(50)] = 747,
  [SMALL_STATE(51)] = 753,
  [SMALL_STATE(52)] = 761,
  [SMALL_STATE(53)] = 767,
  [SMALL_STATE(54)] = 775,
  [SMALL_STATE(55)] = 785,
  [SMALL_STATE(56)] = 791,
  [SMALL_STATE(57)] = 799,
  [SMALL_STATE(58)] = 805,
  [SMALL_STATE(59)] = 815,
  [SMALL_STATE(60)] = 821,
  [SMALL_STATE(61)] = 827,
  [SMALL_STATE(62)] = 837,
  [SMALL_STATE(63)] = 843,
  [SMALL_STATE(64)] = 849,
  [SMALL_STATE(65)] = 855,
  [SMALL_STATE(66)] = 861,
  [SMALL_STATE(67)] = 867,
  [SMALL_STATE(68)] = 873,
  [SMALL_STATE(69)] = 883,
  [SMALL_STATE(70)] = 889,
  [SMALL_STATE(71)] = 899,
  [SMALL_STATE(72)] = 903,
  [SMALL_STATE(73)] = 907,
  [SMALL_STATE(74)] = 911,
  [SMALL_STATE(75)] = 915,
  [SMALL_STATE(76)] = 919,
  [SMALL_STATE(77)] = 923,
  [SMALL_STATE(78)] = 927,
  [SMALL_STATE(79)] = 931,
  [SMALL_STATE(80)] = 935,
  [SMALL_STATE(81)] = 939,
  [SMALL_STATE(82)] = 943,
  [SMALL_STATE(83)] = 947,
  [SMALL_STATE(84)] = 951,
  [SMALL_STATE(85)] = 955,
  [SMALL_STATE(86)] = 959,
  [SMALL_STATE(87)] = 963,
  [SMALL_STATE(88)] = 967,
  [SMALL_STATE(89)] = 971,
  [SMALL_STATE(90)] = 975,
  [SMALL_STATE(91)] = 979,
  [SMALL_STATE(92)] = 983,
  [SMALL_STATE(93)] = 987,
  [SMALL_STATE(94)] = 991,
  [SMALL_STATE(95)] = 995,
  [SMALL_STATE(96)] = 999,
  [SMALL_STATE(97)] = 1003,
  [SMALL_STATE(98)] = 1007,
  [SMALL_STATE(99)] = 1011,
  [SMALL_STATE(100)] = 1015,
  [SMALL_STATE(101)] = 1019,
  [SMALL_STATE(102)] = 1023,
  [SMALL_STATE(103)] = 1027,
  [SMALL_STATE(104)] = 1031,
  [SMALL_STATE(105)] = 1035,
  [SMALL_STATE(106)] = 1039,
  [SMALL_STATE(107)] = 1043,
  [SMALL_STATE(108)] = 1047,
  [SMALL_STATE(109)] = 1051,
  [SMALL_STATE(110)] = 1055,
  [SMALL_STATE(111)] = 1059,
  [SMALL_STATE(112)] = 1063,
  [SMALL_STATE(113)] = 1067,
  [SMALL_STATE(114)] = 1071,
  [SMALL_STATE(115)] = 1075,
  [SMALL_STATE(116)] = 1079,
  [SMALL_STATE(117)] = 1083,
  [SMALL_STATE(118)] = 1087,
  [SMALL_STATE(119)] = 1091,
  [SMALL_STATE(120)] = 1095,
  [SMALL_STATE(121)] = 1099,
  [SMALL_STATE(122)] = 1103,
  [SMALL_STATE(123)] = 1107,
  [SMALL_STATE(124)] = 1111,
  [SMALL_STATE(125)] = 1115,
  [SMALL_STATE(126)] = 1119,
  [SMALL_STATE(127)] = 1123,
  [SMALL_STATE(128)] = 1127,
  [SMALL_STATE(129)] = 1131,
  [SMALL_STATE(130)] = 1135,
  [SMALL_STATE(131)] = 1139,
  [SMALL_STATE(132)] = 1143,
  [SMALL_STATE(133)] = 1147,
  [SMALL_STATE(134)] = 1151,
  [SMALL_STATE(135)] = 1155,
  [SMALL_STATE(136)] = 1159,
  [SMALL_STATE(137)] = 1163,
  [SMALL_STATE(138)] = 1167,
  [SMALL_STATE(139)] = 1171,
  [SMALL_STATE(140)] = 1175,
  [SMALL_STATE(141)] = 1179,
  [SMALL_STATE(142)] = 1183,
  [SMALL_STATE(143)] = 1187,
  [SMALL_STATE(144)] = 1191,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 4, .production_id = 6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 4, .production_id = 3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 5, .production_id = 8),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(10),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(22),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(17),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(23),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 13),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_directive, 13),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 12),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_directive, 12),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 11),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_directive, 11),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 9, .production_id = 10),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 9, .production_id = 10),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 8, .production_id = 8),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 8, .production_id = 8),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 8, .production_id = 7),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 8, .production_id = 7),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_directive, 7, .production_id = 4),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial_directive, 7, .production_id = 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 7, .production_id = 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 7, .production_id = 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_directive, 7, .production_id = 2),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_directive, 7, .production_id = 2),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 4, .production_id = 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 4, .production_id = 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 4),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_directive, 4),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 4),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 4),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 3),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_directive, 3),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(54),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [202] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 5, .production_id = 7),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 5, .production_id = 9),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 4, .production_id = 5),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 6, .production_id = 10),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jqtpl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
