#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 163
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 1
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 14
#define PRODUCTION_ID_COUNT 4

enum {
  aux_sym_code_token1 = 1,
  anon_sym_LBRACE_LBRACE = 2,
  anon_sym_EQ = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_html = 5,
  anon_sym_LBRACE_LBRACE_BANG = 6,
  anon_sym_if = 7,
  anon_sym_SLASH = 8,
  anon_sym_RBRACE_RBRACE2 = 9,
  anon_sym_else = 10,
  anon_sym_each = 11,
  anon_sym_LPAREN = 12,
  aux_sym_each_directive_token1 = 13,
  anon_sym_COMMA = 14,
  aux_sym_each_directive_token2 = 15,
  anon_sym_RPAREN = 16,
  anon_sym_partial = 17,
  anon_sym_LPAREN2 = 18,
  aux_sym_partial_directive_token1 = 19,
  sym_template = 20,
  sym__blerg = 21,
  sym_code = 22,
  sym_content = 23,
  sym_output_directive = 24,
  sym_html_directive = 25,
  sym_comment_directive = 26,
  sym_if_directive = 27,
  sym_else_directive = 28,
  sym_each_directive = 29,
  sym_partial_directive = 30,
  aux_sym_template_repeat1 = 31,
  aux_sym__blerg_repeat1 = 32,
  aux_sym_code_repeat1 = 33,
  aux_sym_if_directive_repeat1 = 34,
  alias_sym_comment = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_code_token1] = "code_token1",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_EQ] = "=",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_html] = "html",
  [anon_sym_LBRACE_LBRACE_BANG] = "{{!",
  [anon_sym_if] = "if",
  [anon_sym_SLASH] = "/",
  [anon_sym_RBRACE_RBRACE2] = "}}",
  [anon_sym_else] = "else",
  [anon_sym_each] = "each",
  [anon_sym_LPAREN] = "(",
  [aux_sym_each_directive_token1] = "each_directive_token1",
  [anon_sym_COMMA] = ",",
  [aux_sym_each_directive_token2] = "each_directive_token2",
  [anon_sym_RPAREN] = ")",
  [anon_sym_partial] = "partial",
  [anon_sym_LPAREN2] = "(",
  [aux_sym_partial_directive_token1] = "code",
  [sym_template] = "template",
  [sym__blerg] = "_blerg",
  [sym_code] = "code",
  [sym_content] = "content",
  [sym_output_directive] = "output_directive",
  [sym_html_directive] = "html_directive",
  [sym_comment_directive] = "comment_directive",
  [sym_if_directive] = "if_directive",
  [sym_else_directive] = "else_directive",
  [sym_each_directive] = "each_directive",
  [sym_partial_directive] = "partial_directive",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym__blerg_repeat1] = "_blerg_repeat1",
  [aux_sym_code_repeat1] = "code_repeat1",
  [aux_sym_if_directive_repeat1] = "if_directive_repeat1",
  [alias_sym_comment] = "comment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_code_token1] = aux_sym_code_token1,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_html] = anon_sym_html,
  [anon_sym_LBRACE_LBRACE_BANG] = anon_sym_LBRACE_LBRACE_BANG,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_RBRACE_RBRACE2] = anon_sym_RBRACE_RBRACE,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_each] = anon_sym_each,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_each_directive_token1] = aux_sym_each_directive_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_each_directive_token2] = aux_sym_each_directive_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_partial] = anon_sym_partial,
  [anon_sym_LPAREN2] = anon_sym_LPAREN,
  [aux_sym_partial_directive_token1] = sym_code,
  [sym_template] = sym_template,
  [sym__blerg] = sym__blerg,
  [sym_code] = sym_code,
  [sym_content] = sym_content,
  [sym_output_directive] = sym_output_directive,
  [sym_html_directive] = sym_html_directive,
  [sym_comment_directive] = sym_comment_directive,
  [sym_if_directive] = sym_if_directive,
  [sym_else_directive] = sym_else_directive,
  [sym_each_directive] = sym_each_directive,
  [sym_partial_directive] = sym_partial_directive,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym__blerg_repeat1] = aux_sym__blerg_repeat1,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
  [aux_sym_if_directive_repeat1] = aux_sym_if_directive_repeat1,
  [alias_sym_comment] = alias_sym_comment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_code_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_html] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_each] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_partial] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_partial_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__blerg] = {
    .visible = false,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_html_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_else_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_each_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__blerg_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_comment] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_bindings = 1,
  field_condition = 2,
  field_path = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bindings] = "bindings",
  [field_condition] = "condition",
  [field_path] = "path",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 2},
  [1] =
    {field_bindings, 3},
    {field_path, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_comment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_code, 2,
    sym_code,
    alias_sym_comment,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 10,
  [11] = 10,
  [12] = 8,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 15,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 20,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 26,
  [35] = 35,
  [36] = 36,
  [37] = 33,
  [38] = 29,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 35,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 31,
  [53] = 46,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 32,
  [60] = 60,
  [61] = 61,
  [62] = 30,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 57,
  [68] = 68,
  [69] = 40,
  [70] = 41,
  [71] = 44,
  [72] = 58,
  [73] = 26,
  [74] = 65,
  [75] = 75,
  [76] = 68,
  [77] = 39,
  [78] = 55,
  [79] = 49,
  [80] = 51,
  [81] = 47,
  [82] = 50,
  [83] = 54,
  [84] = 75,
  [85] = 43,
  [86] = 42,
  [87] = 61,
  [88] = 64,
  [89] = 45,
  [90] = 90,
  [91] = 90,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 93,
  [96] = 94,
  [97] = 92,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 99,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 102,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 103,
  [122] = 105,
  [123] = 123,
  [124] = 107,
  [125] = 125,
  [126] = 110,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 125,
  [131] = 120,
  [132] = 104,
  [133] = 133,
  [134] = 98,
  [135] = 119,
  [136] = 136,
  [137] = 118,
  [138] = 138,
  [139] = 129,
  [140] = 140,
  [141] = 113,
  [142] = 112,
  [143] = 133,
  [144] = 117,
  [145] = 128,
  [146] = 116,
  [147] = 147,
  [148] = 115,
  [149] = 149,
  [150] = 127,
  [151] = 111,
  [152] = 152,
  [153] = 153,
  [154] = 152,
  [155] = 140,
  [156] = 123,
  [157] = 157,
  [158] = 149,
  [159] = 106,
  [160] = 109,
  [161] = 136,
  [162] = 153,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(5);
      if (lookahead == 'h') ADVANCE(18);
      if (lookahead == 'i') ADVANCE(10);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 1:
      if (lookahead == '(') ADVANCE(47);
      END_STATE();
    case 2:
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == '}') ADVANCE(23);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 3:
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == ')') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '(') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 10:
      if (lookahead == 'f') ADVANCE(42);
      END_STATE();
    case 11:
      if (lookahead == 'h') ADVANCE(46);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(7);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 't') ADVANCE(15);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(12);
      END_STATE();
    case 20:
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == '}') ADVANCE(44);
      END_STATE();
    case 24:
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(52);
      END_STATE();
    case 26:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(49);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      if (lookahead == '(') ADVANCE(55);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == ',') ADVANCE(50);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == '{') ADVANCE(20);
      if (lookahead == '}') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_code_token1);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '{') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '{') ADVANCE(31);
      if (lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '}') ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead == '{' ||
          lookahead == '}') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_code_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead == '!') ADVANCE(41);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_html);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_BANG);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_each);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_each_directive_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(49);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_each_directive_token1);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_each_directive_token2);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_each_directive_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_partial);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LPAREN2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_partial_directive_token1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_partial_directive_token1);
      if (lookahead == '(') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(57);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 28},
  [4] = {.lex_state = 28},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 28},
  [10] = {.lex_state = 28},
  [11] = {.lex_state = 28},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 21},
  [32] = {.lex_state = 28},
  [33] = {.lex_state = 21},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 21},
  [36] = {.lex_state = 21},
  [37] = {.lex_state = 21},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 28},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 28},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 28},
  [48] = {.lex_state = 21},
  [49] = {.lex_state = 28},
  [50] = {.lex_state = 28},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 21},
  [53] = {.lex_state = 21},
  [54] = {.lex_state = 28},
  [55] = {.lex_state = 28},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 24},
  [59] = {.lex_state = 28},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 28},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 21},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 28},
  [70] = {.lex_state = 28},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 24},
  [73] = {.lex_state = 21},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 24},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 28},
  [78] = {.lex_state = 28},
  [79] = {.lex_state = 28},
  [80] = {.lex_state = 28},
  [81] = {.lex_state = 28},
  [82] = {.lex_state = 28},
  [83] = {.lex_state = 28},
  [84] = {.lex_state = 24},
  [85] = {.lex_state = 28},
  [86] = {.lex_state = 28},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 28},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 2},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 25},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 2},
  [117] = {.lex_state = 2},
  [118] = {.lex_state = 2},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 2},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 56},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 26},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 56},
  [144] = {.lex_state = 2},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 2},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 2},
  [153] = {.lex_state = 1},
  [154] = {.lex_state = 2},
  [155] = {.lex_state = 0},
  [156] = {.lex_state = 0},
  [157] = {.lex_state = 0},
  [158] = {.lex_state = 0},
  [159] = {.lex_state = 25},
  [160] = {.lex_state = 0},
  [161] = {.lex_state = 26},
  [162] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_html] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_each] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_partial] = ACTIONS(1),
    [anon_sym_LPAREN2] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(100),
    [sym__blerg] = STATE(4),
    [sym_content] = STATE(4),
    [sym_output_directive] = STATE(4),
    [sym_html_directive] = STATE(4),
    [sym_comment_directive] = STATE(4),
    [sym_if_directive] = STATE(4),
    [sym_each_directive] = STATE(4),
    [sym_partial_directive] = STATE(4),
    [aux_sym_template_repeat1] = STATE(4),
    [aux_sym__blerg_repeat1] = STATE(4),
    [aux_sym_code_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_code_token1] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(13), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(64), 1,
      sym__blerg,
    STATE(61), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [30] = 7,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(88), 1,
      sym__blerg,
    STATE(87), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [60] = 6,
    ACTIONS(5), 1,
      aux_sym_code_token1,
    ACTIONS(7), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(29), 1,
      aux_sym_code_repeat1,
    STATE(7), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [88] = 7,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(21), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(76), 1,
      sym__blerg,
    STATE(57), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [118] = 7,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(23), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(68), 1,
      sym__blerg,
    STATE(67), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [148] = 6,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym_code_token1,
    ACTIONS(30), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(33), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    STATE(29), 1,
      aux_sym_code_repeat1,
    STATE(7), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [176] = 5,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(36), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(10), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [201] = 5,
    ACTIONS(38), 1,
      aux_sym_code_token1,
    ACTIONS(41), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(44), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(9), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [226] = 5,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(47), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(9), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [251] = 5,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(49), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(9), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [276] = 5,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(51), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(11), 10,
      sym__blerg,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym_template_repeat1,
      aux_sym__blerg_repeat1,
  [301] = 6,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(53), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(138), 1,
      sym__blerg,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [327] = 6,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(55), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(147), 1,
      sym__blerg,
    STATE(16), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [353] = 6,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      aux_sym_code_token1,
    ACTIONS(62), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    STATE(29), 1,
      aux_sym_code_repeat1,
    STATE(15), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [379] = 5,
    ACTIONS(11), 1,
      aux_sym_code_token1,
    ACTIONS(15), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    ACTIONS(68), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(17), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [402] = 5,
    ACTIONS(70), 1,
      aux_sym_code_token1,
    ACTIONS(73), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(76), 1,
      anon_sym_LBRACE_LBRACE_BANG,
    STATE(38), 1,
      aux_sym_code_repeat1,
    STATE(17), 8,
      sym_content,
      sym_output_directive,
      sym_html_directive,
      sym_comment_directive,
      sym_if_directive,
      sym_each_directive,
      sym_partial_directive,
      aux_sym__blerg_repeat1,
  [425] = 7,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(85), 1,
      anon_sym_SLASH,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
  [447] = 7,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(93), 1,
      anon_sym_SLASH,
  [469] = 7,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(95), 1,
      anon_sym_SLASH,
  [491] = 7,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(97), 1,
      anon_sym_SLASH,
  [513] = 6,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(99), 1,
      anon_sym_SLASH,
  [532] = 6,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(101), 1,
      anon_sym_SLASH,
  [551] = 6,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(103), 1,
      anon_sym_SLASH,
  [570] = 6,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
    ACTIONS(105), 1,
      anon_sym_SLASH,
  [589] = 4,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 1,
      aux_sym_code_token1,
    STATE(26), 1,
      aux_sym_code_repeat1,
    ACTIONS(112), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [603] = 5,
    ACTIONS(114), 1,
      anon_sym_EQ,
    ACTIONS(116), 1,
      anon_sym_html,
    ACTIONS(118), 1,
      anon_sym_if,
    ACTIONS(120), 1,
      anon_sym_each,
    ACTIONS(122), 1,
      anon_sym_partial,
  [619] = 5,
    ACTIONS(79), 1,
      anon_sym_EQ,
    ACTIONS(81), 1,
      anon_sym_html,
    ACTIONS(83), 1,
      anon_sym_if,
    ACTIONS(89), 1,
      anon_sym_each,
    ACTIONS(91), 1,
      anon_sym_partial,
  [635] = 3,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(26), 1,
      aux_sym_code_repeat1,
    ACTIONS(126), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [647] = 2,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [656] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(134), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(112), 1,
      sym_code,
  [669] = 2,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [678] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(140), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(111), 1,
      sym_code,
  [691] = 3,
    ACTIONS(142), 1,
      aux_sym_code_token1,
    STATE(34), 1,
      aux_sym_code_repeat1,
    ACTIONS(112), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [702] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(145), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(113), 1,
      sym_code,
  [715] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(147), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(108), 1,
      sym_code,
  [728] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(149), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(151), 1,
      sym_code,
  [741] = 2,
    STATE(34), 1,
      aux_sym_code_repeat1,
    ACTIONS(126), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [750] = 2,
    ACTIONS(151), 1,
      ts_builtin_sym_end,
    ACTIONS(153), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [759] = 2,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
    ACTIONS(157), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [768] = 2,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [777] = 2,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [786] = 2,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [795] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [804] = 2,
    ACTIONS(175), 1,
      ts_builtin_sym_end,
    ACTIONS(177), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [813] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(179), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(140), 1,
      sym_code,
  [826] = 2,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [835] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(185), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(141), 1,
      sym_code,
  [848] = 2,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    ACTIONS(189), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [857] = 2,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [866] = 2,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(197), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [875] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(199), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(142), 1,
      sym_code,
  [888] = 4,
    ACTIONS(132), 1,
      aux_sym_code_token1,
    ACTIONS(201), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(155), 1,
      sym_code,
  [901] = 2,
    ACTIONS(203), 1,
      ts_builtin_sym_end,
    ACTIONS(205), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [910] = 2,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [919] = 2,
    ACTIONS(211), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [927] = 2,
    ACTIONS(214), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [935] = 3,
    ACTIONS(216), 1,
      aux_sym_code_token1,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(156), 1,
      sym_code,
  [945] = 1,
    ACTIONS(138), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [951] = 2,
    ACTIONS(218), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [959] = 2,
    ACTIONS(220), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [967] = 1,
    ACTIONS(130), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [973] = 2,
    ACTIONS(222), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [981] = 2,
    ACTIONS(220), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(60), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [989] = 2,
    ACTIONS(224), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [997] = 3,
    ACTIONS(226), 1,
      aux_sym_code_token1,
    ACTIONS(228), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(73), 1,
      aux_sym_code_repeat1,
  [1007] = 2,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1015] = 2,
    ACTIONS(230), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(65), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1023] = 1,
    ACTIONS(157), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1029] = 1,
    ACTIONS(161), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1035] = 1,
    ACTIONS(173), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1041] = 3,
    ACTIONS(216), 1,
      aux_sym_code_token1,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(123), 1,
      sym_code,
  [1051] = 3,
    ACTIONS(112), 1,
      anon_sym_RBRACE_RBRACE,
    ACTIONS(232), 1,
      aux_sym_code_token1,
    STATE(73), 1,
      aux_sym_code_repeat1,
  [1061] = 2,
    ACTIONS(235), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1069] = 3,
    ACTIONS(216), 1,
      aux_sym_code_token1,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(115), 1,
      sym_code,
  [1079] = 2,
    ACTIONS(214), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(74), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1087] = 1,
    ACTIONS(153), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1093] = 1,
    ACTIONS(209), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1099] = 1,
    ACTIONS(189), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1105] = 1,
    ACTIONS(197), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1111] = 1,
    ACTIONS(183), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1117] = 1,
    ACTIONS(193), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1123] = 1,
    ACTIONS(205), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1129] = 3,
    ACTIONS(216), 1,
      aux_sym_code_token1,
    STATE(66), 1,
      aux_sym_code_repeat1,
    STATE(148), 1,
      sym_code,
  [1139] = 1,
    ACTIONS(169), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1145] = 1,
    ACTIONS(165), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1151] = 2,
    ACTIONS(237), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(56), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1159] = 2,
    ACTIONS(237), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(63), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [1167] = 1,
    ACTIONS(177), 3,
      aux_sym_code_token1,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_LBRACE_BANG,
  [1173] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(239), 1,
      anon_sym_SLASH,
  [1180] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(241), 1,
      anon_sym_SLASH,
  [1187] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(243), 1,
      anon_sym_SLASH,
  [1194] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(245), 1,
      anon_sym_SLASH,
  [1201] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(247), 1,
      anon_sym_SLASH,
  [1208] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(249), 1,
      anon_sym_SLASH,
  [1215] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(251), 1,
      anon_sym_SLASH,
  [1222] = 2,
    ACTIONS(87), 1,
      anon_sym_else,
    ACTIONS(253), 1,
      anon_sym_SLASH,
  [1229] = 1,
    ACTIONS(255), 1,
      anon_sym_RPAREN,
  [1233] = 1,
    ACTIONS(257), 1,
      anon_sym_each,
  [1237] = 1,
    ACTIONS(259), 1,
      ts_builtin_sym_end,
  [1241] = 1,
    ACTIONS(261), 1,
      anon_sym_each,
  [1245] = 1,
    ACTIONS(263), 1,
      anon_sym_RBRACE_RBRACE2,
  [1249] = 1,
    ACTIONS(265), 1,
      anon_sym_RBRACE_RBRACE2,
  [1253] = 1,
    ACTIONS(267), 1,
      anon_sym_each,
  [1257] = 1,
    ACTIONS(269), 1,
      anon_sym_RBRACE_RBRACE2,
  [1261] = 1,
    ACTIONS(271), 1,
      aux_sym_each_directive_token2,
  [1265] = 1,
    ACTIONS(273), 1,
      anon_sym_if,
  [1269] = 1,
    ACTIONS(275), 1,
      anon_sym_RBRACE_RBRACE,
  [1273] = 1,
    ACTIONS(277), 1,
      anon_sym_COMMA,
  [1277] = 1,
    ACTIONS(279), 1,
      anon_sym_if,
  [1281] = 1,
    ACTIONS(281), 1,
      anon_sym_RBRACE_RBRACE,
  [1285] = 1,
    ACTIONS(283), 1,
      anon_sym_RBRACE_RBRACE,
  [1289] = 1,
    ACTIONS(285), 1,
      anon_sym_RBRACE_RBRACE,
  [1293] = 1,
    ACTIONS(287), 1,
      anon_sym_RBRACE_RBRACE2,
  [1297] = 1,
    ACTIONS(289), 1,
      anon_sym_RBRACE_RBRACE,
  [1301] = 1,
    ACTIONS(291), 1,
      anon_sym_RBRACE_RBRACE2,
  [1305] = 1,
    ACTIONS(293), 1,
      anon_sym_RBRACE_RBRACE2,
  [1309] = 1,
    ACTIONS(295), 1,
      anon_sym_RBRACE_RBRACE2,
  [1313] = 1,
    ACTIONS(297), 1,
      anon_sym_RBRACE_RBRACE2,
  [1317] = 1,
    ACTIONS(299), 1,
      anon_sym_RBRACE_RBRACE2,
  [1321] = 1,
    ACTIONS(301), 1,
      anon_sym_RBRACE_RBRACE2,
  [1325] = 1,
    ACTIONS(303), 1,
      anon_sym_RBRACE_RBRACE2,
  [1329] = 1,
    ACTIONS(305), 1,
      anon_sym_RBRACE_RBRACE,
  [1333] = 1,
    ACTIONS(307), 1,
      anon_sym_if,
  [1337] = 1,
    ACTIONS(309), 1,
      anon_sym_if,
  [1341] = 1,
    ACTIONS(311), 1,
      anon_sym_if,
  [1345] = 1,
    ACTIONS(313), 1,
      anon_sym_if,
  [1349] = 1,
    ACTIONS(315), 1,
      anon_sym_if,
  [1353] = 1,
    ACTIONS(317), 1,
      anon_sym_if,
  [1357] = 1,
    ACTIONS(319), 1,
      anon_sym_if,
  [1361] = 1,
    ACTIONS(321), 1,
      anon_sym_RBRACE_RBRACE2,
  [1365] = 1,
    ACTIONS(323), 1,
      anon_sym_each,
  [1369] = 1,
    ACTIONS(325), 1,
      aux_sym_partial_directive_token1,
  [1373] = 1,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
  [1377] = 1,
    ACTIONS(329), 1,
      anon_sym_RBRACE_RBRACE2,
  [1381] = 1,
    ACTIONS(331), 1,
      aux_sym_each_directive_token1,
  [1385] = 1,
    ACTIONS(333), 1,
      anon_sym_RBRACE_RBRACE2,
  [1389] = 1,
    ACTIONS(335), 1,
      anon_sym_LBRACE_LBRACE,
  [1393] = 1,
    ACTIONS(337), 1,
      anon_sym_if,
  [1397] = 1,
    ACTIONS(339), 1,
      anon_sym_RBRACE_RBRACE,
  [1401] = 1,
    ACTIONS(341), 1,
      anon_sym_RBRACE_RBRACE,
  [1405] = 1,
    ACTIONS(343), 1,
      anon_sym_RBRACE_RBRACE,
  [1409] = 1,
    ACTIONS(345), 1,
      aux_sym_partial_directive_token1,
  [1413] = 1,
    ACTIONS(347), 1,
      anon_sym_RBRACE_RBRACE2,
  [1417] = 1,
    ACTIONS(349), 1,
      anon_sym_if,
  [1421] = 1,
    ACTIONS(351), 1,
      anon_sym_RBRACE_RBRACE2,
  [1425] = 1,
    ACTIONS(353), 1,
      anon_sym_LBRACE_LBRACE,
  [1429] = 1,
    ACTIONS(355), 1,
      anon_sym_RBRACE_RBRACE,
  [1433] = 1,
    ACTIONS(357), 1,
      anon_sym_RPAREN,
  [1437] = 1,
    ACTIONS(359), 1,
      anon_sym_if,
  [1441] = 1,
    ACTIONS(361), 1,
      anon_sym_RBRACE_RBRACE,
  [1445] = 1,
    ACTIONS(363), 1,
      anon_sym_LPAREN2,
  [1449] = 1,
    ACTIONS(365), 1,
      anon_sym_LPAREN,
  [1453] = 1,
    ACTIONS(367), 1,
      anon_sym_LPAREN2,
  [1457] = 1,
    ACTIONS(369), 1,
      anon_sym_RBRACE_RBRACE,
  [1461] = 1,
    ACTIONS(371), 1,
      anon_sym_RBRACE_RBRACE,
  [1465] = 1,
    ACTIONS(87), 1,
      anon_sym_else,
  [1469] = 1,
    ACTIONS(373), 1,
      anon_sym_RPAREN,
  [1473] = 1,
    ACTIONS(375), 1,
      aux_sym_each_directive_token2,
  [1477] = 1,
    ACTIONS(377), 1,
      anon_sym_COMMA,
  [1481] = 1,
    ACTIONS(379), 1,
      aux_sym_each_directive_token1,
  [1485] = 1,
    ACTIONS(381), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 88,
  [SMALL_STATE(6)] = 118,
  [SMALL_STATE(7)] = 148,
  [SMALL_STATE(8)] = 176,
  [SMALL_STATE(9)] = 201,
  [SMALL_STATE(10)] = 226,
  [SMALL_STATE(11)] = 251,
  [SMALL_STATE(12)] = 276,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 327,
  [SMALL_STATE(15)] = 353,
  [SMALL_STATE(16)] = 379,
  [SMALL_STATE(17)] = 402,
  [SMALL_STATE(18)] = 425,
  [SMALL_STATE(19)] = 447,
  [SMALL_STATE(20)] = 469,
  [SMALL_STATE(21)] = 491,
  [SMALL_STATE(22)] = 513,
  [SMALL_STATE(23)] = 532,
  [SMALL_STATE(24)] = 551,
  [SMALL_STATE(25)] = 570,
  [SMALL_STATE(26)] = 589,
  [SMALL_STATE(27)] = 603,
  [SMALL_STATE(28)] = 619,
  [SMALL_STATE(29)] = 635,
  [SMALL_STATE(30)] = 647,
  [SMALL_STATE(31)] = 656,
  [SMALL_STATE(32)] = 669,
  [SMALL_STATE(33)] = 678,
  [SMALL_STATE(34)] = 691,
  [SMALL_STATE(35)] = 702,
  [SMALL_STATE(36)] = 715,
  [SMALL_STATE(37)] = 728,
  [SMALL_STATE(38)] = 741,
  [SMALL_STATE(39)] = 750,
  [SMALL_STATE(40)] = 759,
  [SMALL_STATE(41)] = 768,
  [SMALL_STATE(42)] = 777,
  [SMALL_STATE(43)] = 786,
  [SMALL_STATE(44)] = 795,
  [SMALL_STATE(45)] = 804,
  [SMALL_STATE(46)] = 813,
  [SMALL_STATE(47)] = 826,
  [SMALL_STATE(48)] = 835,
  [SMALL_STATE(49)] = 848,
  [SMALL_STATE(50)] = 857,
  [SMALL_STATE(51)] = 866,
  [SMALL_STATE(52)] = 875,
  [SMALL_STATE(53)] = 888,
  [SMALL_STATE(54)] = 901,
  [SMALL_STATE(55)] = 910,
  [SMALL_STATE(56)] = 919,
  [SMALL_STATE(57)] = 927,
  [SMALL_STATE(58)] = 935,
  [SMALL_STATE(59)] = 945,
  [SMALL_STATE(60)] = 951,
  [SMALL_STATE(61)] = 959,
  [SMALL_STATE(62)] = 967,
  [SMALL_STATE(63)] = 973,
  [SMALL_STATE(64)] = 981,
  [SMALL_STATE(65)] = 989,
  [SMALL_STATE(66)] = 997,
  [SMALL_STATE(67)] = 1007,
  [SMALL_STATE(68)] = 1015,
  [SMALL_STATE(69)] = 1023,
  [SMALL_STATE(70)] = 1029,
  [SMALL_STATE(71)] = 1035,
  [SMALL_STATE(72)] = 1041,
  [SMALL_STATE(73)] = 1051,
  [SMALL_STATE(74)] = 1061,
  [SMALL_STATE(75)] = 1069,
  [SMALL_STATE(76)] = 1079,
  [SMALL_STATE(77)] = 1087,
  [SMALL_STATE(78)] = 1093,
  [SMALL_STATE(79)] = 1099,
  [SMALL_STATE(80)] = 1105,
  [SMALL_STATE(81)] = 1111,
  [SMALL_STATE(82)] = 1117,
  [SMALL_STATE(83)] = 1123,
  [SMALL_STATE(84)] = 1129,
  [SMALL_STATE(85)] = 1139,
  [SMALL_STATE(86)] = 1145,
  [SMALL_STATE(87)] = 1151,
  [SMALL_STATE(88)] = 1159,
  [SMALL_STATE(89)] = 1167,
  [SMALL_STATE(90)] = 1173,
  [SMALL_STATE(91)] = 1180,
  [SMALL_STATE(92)] = 1187,
  [SMALL_STATE(93)] = 1194,
  [SMALL_STATE(94)] = 1201,
  [SMALL_STATE(95)] = 1208,
  [SMALL_STATE(96)] = 1215,
  [SMALL_STATE(97)] = 1222,
  [SMALL_STATE(98)] = 1229,
  [SMALL_STATE(99)] = 1233,
  [SMALL_STATE(100)] = 1237,
  [SMALL_STATE(101)] = 1241,
  [SMALL_STATE(102)] = 1245,
  [SMALL_STATE(103)] = 1249,
  [SMALL_STATE(104)] = 1253,
  [SMALL_STATE(105)] = 1257,
  [SMALL_STATE(106)] = 1261,
  [SMALL_STATE(107)] = 1265,
  [SMALL_STATE(108)] = 1269,
  [SMALL_STATE(109)] = 1273,
  [SMALL_STATE(110)] = 1277,
  [SMALL_STATE(111)] = 1281,
  [SMALL_STATE(112)] = 1285,
  [SMALL_STATE(113)] = 1289,
  [SMALL_STATE(114)] = 1293,
  [SMALL_STATE(115)] = 1297,
  [SMALL_STATE(116)] = 1301,
  [SMALL_STATE(117)] = 1305,
  [SMALL_STATE(118)] = 1309,
  [SMALL_STATE(119)] = 1313,
  [SMALL_STATE(120)] = 1317,
  [SMALL_STATE(121)] = 1321,
  [SMALL_STATE(122)] = 1325,
  [SMALL_STATE(123)] = 1329,
  [SMALL_STATE(124)] = 1333,
  [SMALL_STATE(125)] = 1337,
  [SMALL_STATE(126)] = 1341,
  [SMALL_STATE(127)] = 1345,
  [SMALL_STATE(128)] = 1349,
  [SMALL_STATE(129)] = 1353,
  [SMALL_STATE(130)] = 1357,
  [SMALL_STATE(131)] = 1361,
  [SMALL_STATE(132)] = 1365,
  [SMALL_STATE(133)] = 1369,
  [SMALL_STATE(134)] = 1373,
  [SMALL_STATE(135)] = 1377,
  [SMALL_STATE(136)] = 1381,
  [SMALL_STATE(137)] = 1385,
  [SMALL_STATE(138)] = 1389,
  [SMALL_STATE(139)] = 1393,
  [SMALL_STATE(140)] = 1397,
  [SMALL_STATE(141)] = 1401,
  [SMALL_STATE(142)] = 1405,
  [SMALL_STATE(143)] = 1409,
  [SMALL_STATE(144)] = 1413,
  [SMALL_STATE(145)] = 1417,
  [SMALL_STATE(146)] = 1421,
  [SMALL_STATE(147)] = 1425,
  [SMALL_STATE(148)] = 1429,
  [SMALL_STATE(149)] = 1433,
  [SMALL_STATE(150)] = 1437,
  [SMALL_STATE(151)] = 1441,
  [SMALL_STATE(152)] = 1445,
  [SMALL_STATE(153)] = 1449,
  [SMALL_STATE(154)] = 1453,
  [SMALL_STATE(155)] = 1457,
  [SMALL_STATE(156)] = 1461,
  [SMALL_STATE(157)] = 1465,
  [SMALL_STATE(158)] = 1469,
  [SMALL_STATE(159)] = 1473,
  [SMALL_STATE(160)] = 1477,
  [SMALL_STATE(161)] = 1481,
  [SMALL_STATE(162)] = 1485,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(29),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(27),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(37),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(38),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(28),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(33),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_directive, 4, .production_id = 2),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_directive, 3),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__blerg_repeat1, 2),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(29),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(27),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(37),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__blerg, 1),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(38),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(28),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__blerg_repeat1, 2), SHIFT_REPEAT(33),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(162),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(154),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(26),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(152),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 4),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 4),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(71),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 4),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_directive, 4),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [142] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(34),
  [145] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 7),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 7),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3, .production_id = 1),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 3, .production_id = 1),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 3),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_directive, 3),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 14),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_directive, 14),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 13),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_each_directive, 13),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_output_directive, 3),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 2),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment_directive, 2),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 9),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 9),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 8),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 8),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 9, .production_id = 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 9, .production_id = 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 8, .production_id = 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 8, .production_id = 2),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 10, .production_id = 2),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_directive, 10, .production_id = 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_directive, 7, .production_id = 3),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_partial_directive, 7, .production_id = 3),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_directive_repeat1, 2), SHIFT_REPEAT(157),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_code, 1),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [232] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2), SHIFT_REPEAT(73),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [259] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 5, .production_id = 2),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [353] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 4),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(158),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(161),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jqtpl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
