#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 103
#define LARGE_STATE_COUNT 21
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 1
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 10
#define PRODUCTION_ID_COUNT 4

enum {
  sym_code = 1,
  sym_content = 2,
  anon_sym_LBRACE_LBRACE_EQ = 3,
  anon_sym_RBRACE_RBRACE = 4,
  anon_sym_LBRACE_LBRACEhtml = 5,
  anon_sym_LBRACE_LBRACE_BANG = 6,
  anon_sym_LBRACE_LBRACEvar = 7,
  anon_sym_LBRACE_LBRACEif = 8,
  anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE = 9,
  anon_sym_LBRACE_LBRACEelse = 10,
  anon_sym_LBRACE_LBRACEeach = 11,
  anon_sym_LPAREN = 12,
  aux_sym_each_directive_token1 = 13,
  anon_sym_COMMA = 14,
  aux_sym_each_directive_token2 = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE = 17,
  anon_sym_LBRACE_LBRACEpartial = 18,
  aux_sym_partial_directive_token1 = 19,
  sym_template = 20,
  sym__node = 21,
  sym_output_directive = 22,
  sym_html_directive = 23,
  sym_comment_directive = 24,
  sym_var_directive = 25,
  sym_if_directive = 26,
  sym_else_directive = 27,
  sym_each_directive = 28,
  sym_partial_directive = 29,
  aux_sym_template_repeat1 = 30,
  aux_sym_if_directive_repeat1 = 31,
  alias_sym_comment = 32,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_code] = "code",
  [sym_content] = "content",
  [anon_sym_LBRACE_LBRACE_EQ] = "{{=",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_LBRACEhtml] = "{{html",
  [anon_sym_LBRACE_LBRACE_BANG] = "{{!",
  [anon_sym_LBRACE_LBRACEvar] = "{{var",
  [anon_sym_LBRACE_LBRACEif] = "{{if",
  [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = "{{/if}}",
  [anon_sym_LBRACE_LBRACEelse] = "{{else",
  [anon_sym_LBRACE_LBRACEeach] = "{{each",
  [anon_sym_LPAREN] = "(",
  [aux_sym_each_directive_token1] = "each_directive_token1",
  [anon_sym_COMMA] = ",",
  [aux_sym_each_directive_token2] = "each_directive_token2",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = "{{/each}}",
  [anon_sym_LBRACE_LBRACEpartial] = "{{partial",
  [aux_sym_partial_directive_token1] = "code",
  [sym_template] = "template",
  [sym__node] = "_node",
  [sym_output_directive] = "output_directive",
  [sym_html_directive] = "html_directive",
  [sym_comment_directive] = "comment_directive",
  [sym_var_directive] = "var_directive",
  [sym_if_directive] = "if_directive",
  [sym_else_directive] = "else_directive",
  [sym_each_directive] = "each_directive",
  [sym_partial_directive] = "partial_directive",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_if_directive_repeat1] = "if_directive_repeat1",
  [alias_sym_comment] = "comment",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_code] = sym_code,
  [sym_content] = sym_content,
  [anon_sym_LBRACE_LBRACE_EQ] = anon_sym_LBRACE_LBRACE_EQ,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACEhtml] = anon_sym_LBRACE_LBRACEhtml,
  [anon_sym_LBRACE_LBRACE_BANG] = anon_sym_LBRACE_LBRACE_BANG,
  [anon_sym_LBRACE_LBRACEvar] = anon_sym_LBRACE_LBRACEvar,
  [anon_sym_LBRACE_LBRACEif] = anon_sym_LBRACE_LBRACEif,
  [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACEelse] = anon_sym_LBRACE_LBRACEelse,
  [anon_sym_LBRACE_LBRACEeach] = anon_sym_LBRACE_LBRACEeach,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [aux_sym_each_directive_token1] = aux_sym_each_directive_token1,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_each_directive_token2] = aux_sym_each_directive_token2,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
  [anon_sym_LBRACE_LBRACEpartial] = anon_sym_LBRACE_LBRACEpartial,
  [aux_sym_partial_directive_token1] = sym_code,
  [sym_template] = sym_template,
  [sym__node] = sym__node,
  [sym_output_directive] = sym_output_directive,
  [sym_html_directive] = sym_html_directive,
  [sym_comment_directive] = sym_comment_directive,
  [sym_var_directive] = sym_var_directive,
  [sym_if_directive] = sym_if_directive,
  [sym_else_directive] = sym_else_directive,
  [sym_each_directive] = sym_each_directive,
  [sym_partial_directive] = sym_partial_directive,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_if_directive_repeat1] = aux_sym_if_directive_repeat1,
  [alias_sym_comment] = alias_sym_comment,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEhtml] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEvar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEelse] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_each_directive_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACEpartial] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_partial_directive_token1] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_output_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_html_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_var_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_if_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_else_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_each_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_partial_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_if_directive_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_comment] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_bindings = 1,
  field_condition = 2,
  field_path = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_bindings] = "bindings",
  [field_condition] = "condition",
  [field_path] = "path",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
  [1] =
    {field_bindings, 2},
    {field_path, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_comment,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 6,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 12,
  [18] = 14,
  [19] = 15,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 29,
  [37] = 26,
  [38] = 24,
  [39] = 23,
  [40] = 32,
  [41] = 25,
  [42] = 27,
  [43] = 28,
  [44] = 30,
  [45] = 33,
  [46] = 22,
  [47] = 34,
  [48] = 21,
  [49] = 31,
  [50] = 35,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 51,
  [55] = 52,
  [56] = 56,
  [57] = 57,
  [58] = 56,
  [59] = 59,
  [60] = 57,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 62,
  [65] = 61,
  [66] = 59,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 67,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 69,
  [79] = 74,
  [80] = 76,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 85,
  [89] = 89,
  [90] = 77,
  [91] = 84,
  [92] = 92,
  [93] = 73,
  [94] = 86,
  [95] = 92,
  [96] = 87,
  [97] = 68,
  [98] = 70,
  [99] = 81,
  [100] = 89,
  [101] = 83,
  [102] = 82,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '(') ADVANCE(47);
      if (lookahead == ')') ADVANCE(51);
      if (lookahead == ',') ADVANCE(49);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(27);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(41);
      if (lookahead == '/') ADVANCE(11);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'h') ADVANCE(23);
      if (lookahead == 'i') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(4);
      if (lookahead == 'v') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == ')') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '(') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(8);
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(20);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(15);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(7);
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(46);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(31);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(6);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(19);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 25:
      if (lookahead == '{') ADVANCE(1);
      END_STATE();
    case 26:
      if (lookahead == '}') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(36);
      END_STATE();
    case 27:
      if (lookahead == '}') ADVANCE(39);
      END_STATE();
    case 28:
      if (lookahead == '}') ADVANCE(44);
      END_STATE();
    case 29:
      if (lookahead == '}') ADVANCE(52);
      END_STATE();
    case 30:
      if (lookahead == '}') ADVANCE(28);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(29);
      END_STATE();
    case 32:
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(50);
      END_STATE();
    case 33:
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(48);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead != 0) ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_code);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '}') ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_content);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEhtml);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_BANG);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEvar);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEif);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEelse);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEeach);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_each_directive_token1);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_each_directive_token2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACEpartial);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_partial_directive_token1);
      if (lookahead == '(') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != ')') ADVANCE(54);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 34},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 34},
  [21] = {.lex_state = 34},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 34},
  [28] = {.lex_state = 34},
  [29] = {.lex_state = 34},
  [30] = {.lex_state = 34},
  [31] = {.lex_state = 34},
  [32] = {.lex_state = 34},
  [33] = {.lex_state = 34},
  [34] = {.lex_state = 34},
  [35] = {.lex_state = 34},
  [36] = {.lex_state = 34},
  [37] = {.lex_state = 34},
  [38] = {.lex_state = 34},
  [39] = {.lex_state = 34},
  [40] = {.lex_state = 34},
  [41] = {.lex_state = 34},
  [42] = {.lex_state = 34},
  [43] = {.lex_state = 34},
  [44] = {.lex_state = 34},
  [45] = {.lex_state = 34},
  [46] = {.lex_state = 34},
  [47] = {.lex_state = 34},
  [48] = {.lex_state = 34},
  [49] = {.lex_state = 34},
  [50] = {.lex_state = 34},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 26},
  [57] = {.lex_state = 26},
  [58] = {.lex_state = 26},
  [59] = {.lex_state = 26},
  [60] = {.lex_state = 26},
  [61] = {.lex_state = 26},
  [62] = {.lex_state = 26},
  [63] = {.lex_state = 26},
  [64] = {.lex_state = 26},
  [65] = {.lex_state = 26},
  [66] = {.lex_state = 26},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 54},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 32},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 33},
  [84] = {.lex_state = 26},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 26},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 26},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 26},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 54},
  [98] = {.lex_state = 32},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 33},
  [102] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(1),
  },
  [1] = {
    [sym_template] = STATE(72),
    [sym__node] = STATE(11),
    [sym_output_directive] = STATE(11),
    [sym_html_directive] = STATE(11),
    [sym_comment_directive] = STATE(11),
    [sym_var_directive] = STATE(11),
    [sym_if_directive] = STATE(11),
    [sym_each_directive] = STATE(11),
    [sym_partial_directive] = STATE(11),
    [aux_sym_template_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_content] = ACTIONS(5),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(11),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(19),
  },
  [2] = {
    [sym__node] = STATE(3),
    [sym_output_directive] = STATE(3),
    [sym_html_directive] = STATE(3),
    [sym_comment_directive] = STATE(3),
    [sym_var_directive] = STATE(3),
    [sym_if_directive] = STATE(3),
    [sym_else_directive] = STATE(51),
    [sym_each_directive] = STATE(3),
    [sym_partial_directive] = STATE(3),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_if_directive_repeat1] = STATE(51),
    [sym_content] = ACTIONS(21),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(33),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [3] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_else_directive] = STATE(55),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [aux_sym_if_directive_repeat1] = STATE(55),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(43),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [4] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_else_directive] = STATE(52),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [aux_sym_if_directive_repeat1] = STATE(52),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(45),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [5] = {
    [sym__node] = STATE(4),
    [sym_output_directive] = STATE(4),
    [sym_html_directive] = STATE(4),
    [sym_comment_directive] = STATE(4),
    [sym_var_directive] = STATE(4),
    [sym_if_directive] = STATE(4),
    [sym_else_directive] = STATE(54),
    [sym_each_directive] = STATE(4),
    [sym_partial_directive] = STATE(4),
    [aux_sym_template_repeat1] = STATE(4),
    [aux_sym_if_directive_repeat1] = STATE(54),
    [sym_content] = ACTIONS(47),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(49),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(35),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [6] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(51),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(54),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(57),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(60),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(63),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(66),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(69),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(69),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(71),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(69),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(74),
  },
  [7] = {
    [sym__node] = STATE(8),
    [sym_output_directive] = STATE(8),
    [sym_html_directive] = STATE(8),
    [sym_comment_directive] = STATE(8),
    [sym_var_directive] = STATE(8),
    [sym_if_directive] = STATE(8),
    [sym_each_directive] = STATE(8),
    [sym_partial_directive] = STATE(8),
    [aux_sym_template_repeat1] = STATE(8),
    [sym_content] = ACTIONS(77),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(79),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(79),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [8] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(81),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(81),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [9] = {
    [sym__node] = STATE(10),
    [sym_output_directive] = STATE(10),
    [sym_html_directive] = STATE(10),
    [sym_comment_directive] = STATE(10),
    [sym_var_directive] = STATE(10),
    [sym_if_directive] = STATE(10),
    [sym_each_directive] = STATE(10),
    [sym_partial_directive] = STATE(10),
    [aux_sym_template_repeat1] = STATE(10),
    [sym_content] = ACTIONS(83),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(85),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(85),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [10] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE] = ACTIONS(87),
    [anon_sym_LBRACE_LBRACEelse] = ACTIONS(87),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [11] = {
    [sym__node] = STATE(13),
    [sym_output_directive] = STATE(13),
    [sym_html_directive] = STATE(13),
    [sym_comment_directive] = STATE(13),
    [sym_var_directive] = STATE(13),
    [sym_if_directive] = STATE(13),
    [sym_each_directive] = STATE(13),
    [sym_partial_directive] = STATE(13),
    [aux_sym_template_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(89),
    [sym_content] = ACTIONS(91),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(9),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(11),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(13),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(15),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(17),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(19),
  },
  [12] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(93),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [13] = {
    [sym__node] = STATE(13),
    [sym_output_directive] = STATE(13),
    [sym_html_directive] = STATE(13),
    [sym_comment_directive] = STATE(13),
    [sym_var_directive] = STATE(13),
    [sym_if_directive] = STATE(13),
    [sym_each_directive] = STATE(13),
    [sym_partial_directive] = STATE(13),
    [aux_sym_template_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym_content] = ACTIONS(95),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(98),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(101),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(104),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(107),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(110),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(113),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(116),
  },
  [14] = {
    [sym__node] = STATE(16),
    [sym_output_directive] = STATE(16),
    [sym_html_directive] = STATE(16),
    [sym_comment_directive] = STATE(16),
    [sym_var_directive] = STATE(16),
    [sym_if_directive] = STATE(16),
    [sym_each_directive] = STATE(16),
    [sym_partial_directive] = STATE(16),
    [aux_sym_template_repeat1] = STATE(16),
    [sym_content] = ACTIONS(119),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(121),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [15] = {
    [sym__node] = STATE(17),
    [sym_output_directive] = STATE(17),
    [sym_html_directive] = STATE(17),
    [sym_comment_directive] = STATE(17),
    [sym_var_directive] = STATE(17),
    [sym_if_directive] = STATE(17),
    [sym_each_directive] = STATE(17),
    [sym_partial_directive] = STATE(17),
    [aux_sym_template_repeat1] = STATE(17),
    [sym_content] = ACTIONS(123),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(125),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [16] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(125),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [17] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(127),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [18] = {
    [sym__node] = STATE(20),
    [sym_output_directive] = STATE(20),
    [sym_html_directive] = STATE(20),
    [sym_comment_directive] = STATE(20),
    [sym_var_directive] = STATE(20),
    [sym_if_directive] = STATE(20),
    [sym_each_directive] = STATE(20),
    [sym_partial_directive] = STATE(20),
    [aux_sym_template_repeat1] = STATE(20),
    [sym_content] = ACTIONS(129),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(131),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [19] = {
    [sym__node] = STATE(12),
    [sym_output_directive] = STATE(12),
    [sym_html_directive] = STATE(12),
    [sym_comment_directive] = STATE(12),
    [sym_var_directive] = STATE(12),
    [sym_if_directive] = STATE(12),
    [sym_each_directive] = STATE(12),
    [sym_partial_directive] = STATE(12),
    [aux_sym_template_repeat1] = STATE(12),
    [sym_content] = ACTIONS(133),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(135),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
  [20] = {
    [sym__node] = STATE(6),
    [sym_output_directive] = STATE(6),
    [sym_html_directive] = STATE(6),
    [sym_comment_directive] = STATE(6),
    [sym_var_directive] = STATE(6),
    [sym_if_directive] = STATE(6),
    [sym_each_directive] = STATE(6),
    [sym_partial_directive] = STATE(6),
    [aux_sym_template_repeat1] = STATE(6),
    [sym_content] = ACTIONS(41),
    [anon_sym_LBRACE_LBRACE_EQ] = ACTIONS(23),
    [anon_sym_LBRACE_LBRACEhtml] = ACTIONS(25),
    [anon_sym_LBRACE_LBRACE_BANG] = ACTIONS(27),
    [anon_sym_LBRACE_LBRACEvar] = ACTIONS(29),
    [anon_sym_LBRACE_LBRACEif] = ACTIONS(31),
    [anon_sym_LBRACE_LBRACEeach] = ACTIONS(37),
    [anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE] = ACTIONS(135),
    [anon_sym_LBRACE_LBRACEpartial] = ACTIONS(39),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(137), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [14] = 1,
    ACTIONS(139), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [28] = 1,
    ACTIONS(141), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [42] = 1,
    ACTIONS(143), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [56] = 1,
    ACTIONS(145), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [70] = 1,
    ACTIONS(147), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [84] = 1,
    ACTIONS(149), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [98] = 1,
    ACTIONS(151), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [112] = 1,
    ACTIONS(153), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [126] = 1,
    ACTIONS(155), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [140] = 1,
    ACTIONS(157), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [154] = 1,
    ACTIONS(159), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [168] = 1,
    ACTIONS(161), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [182] = 1,
    ACTIONS(163), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [196] = 1,
    ACTIONS(165), 11,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEelse,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACE_SLASHeach_RBRACE_RBRACE,
      anon_sym_LBRACE_LBRACEpartial,
  [210] = 1,
    ACTIONS(153), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [222] = 1,
    ACTIONS(147), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [234] = 1,
    ACTIONS(143), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [246] = 1,
    ACTIONS(141), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [258] = 1,
    ACTIONS(159), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [270] = 1,
    ACTIONS(145), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [282] = 1,
    ACTIONS(149), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [294] = 1,
    ACTIONS(151), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [306] = 1,
    ACTIONS(155), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [318] = 1,
    ACTIONS(161), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [330] = 1,
    ACTIONS(139), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [342] = 1,
    ACTIONS(163), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [354] = 1,
    ACTIONS(137), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [366] = 1,
    ACTIONS(157), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [378] = 1,
    ACTIONS(165), 9,
      ts_builtin_sym_end,
      sym_content,
      anon_sym_LBRACE_LBRACE_EQ,
      anon_sym_LBRACE_LBRACEhtml,
      anon_sym_LBRACE_LBRACE_BANG,
      anon_sym_LBRACE_LBRACEvar,
      anon_sym_LBRACE_LBRACEif,
      anon_sym_LBRACE_LBRACEeach,
      anon_sym_LBRACE_LBRACEpartial,
  [390] = 3,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACEelse,
    ACTIONS(43), 1,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
    STATE(53), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [401] = 3,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACEelse,
    ACTIONS(167), 1,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
    STATE(53), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [412] = 3,
    ACTIONS(169), 1,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
    ACTIONS(171), 1,
      anon_sym_LBRACE_LBRACEelse,
    STATE(53), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [423] = 3,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACEelse,
    ACTIONS(45), 1,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
    STATE(53), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [434] = 3,
    ACTIONS(35), 1,
      anon_sym_LBRACE_LBRACEelse,
    ACTIONS(174), 1,
      anon_sym_LBRACE_LBRACE_SLASHif_RBRACE_RBRACE,
    STATE(53), 2,
      sym_else_directive,
      aux_sym_if_directive_repeat1,
  [445] = 2,
    ACTIONS(176), 1,
      sym_code,
    ACTIONS(178), 1,
      anon_sym_RBRACE_RBRACE,
  [452] = 2,
    ACTIONS(180), 1,
      sym_code,
    ACTIONS(182), 1,
      anon_sym_RBRACE_RBRACE,
  [459] = 2,
    ACTIONS(184), 1,
      sym_code,
    ACTIONS(186), 1,
      anon_sym_RBRACE_RBRACE,
  [466] = 2,
    ACTIONS(188), 1,
      sym_code,
    ACTIONS(190), 1,
      anon_sym_RBRACE_RBRACE,
  [473] = 2,
    ACTIONS(192), 1,
      sym_code,
    ACTIONS(194), 1,
      anon_sym_RBRACE_RBRACE,
  [480] = 2,
    ACTIONS(196), 1,
      sym_code,
    ACTIONS(198), 1,
      anon_sym_RBRACE_RBRACE,
  [487] = 2,
    ACTIONS(200), 1,
      sym_code,
    ACTIONS(202), 1,
      anon_sym_RBRACE_RBRACE,
  [494] = 2,
    ACTIONS(204), 1,
      sym_code,
    ACTIONS(206), 1,
      anon_sym_RBRACE_RBRACE,
  [501] = 2,
    ACTIONS(208), 1,
      sym_code,
    ACTIONS(210), 1,
      anon_sym_RBRACE_RBRACE,
  [508] = 2,
    ACTIONS(212), 1,
      sym_code,
    ACTIONS(214), 1,
      anon_sym_RBRACE_RBRACE,
  [515] = 2,
    ACTIONS(216), 1,
      sym_code,
    ACTIONS(218), 1,
      anon_sym_RBRACE_RBRACE,
  [522] = 1,
    ACTIONS(220), 1,
      anon_sym_RBRACE_RBRACE,
  [526] = 1,
    ACTIONS(222), 1,
      aux_sym_partial_directive_token1,
  [530] = 1,
    ACTIONS(224), 1,
      anon_sym_RBRACE_RBRACE,
  [534] = 1,
    ACTIONS(226), 1,
      aux_sym_each_directive_token2,
  [538] = 1,
    ACTIONS(228), 1,
      anon_sym_RBRACE_RBRACE,
  [542] = 1,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
  [546] = 1,
    ACTIONS(232), 1,
      anon_sym_RBRACE_RBRACE,
  [550] = 1,
    ACTIONS(234), 1,
      anon_sym_RBRACE_RBRACE,
  [554] = 1,
    ACTIONS(236), 1,
      anon_sym_RBRACE_RBRACE,
  [558] = 1,
    ACTIONS(238), 1,
      anon_sym_RBRACE_RBRACE,
  [562] = 1,
    ACTIONS(240), 1,
      anon_sym_RBRACE_RBRACE,
  [566] = 1,
    ACTIONS(242), 1,
      anon_sym_RBRACE_RBRACE,
  [570] = 1,
    ACTIONS(244), 1,
      anon_sym_RBRACE_RBRACE,
  [574] = 1,
    ACTIONS(246), 1,
      anon_sym_RBRACE_RBRACE,
  [578] = 1,
    ACTIONS(248), 1,
      anon_sym_LPAREN,
  [582] = 1,
    ACTIONS(250), 1,
      anon_sym_LPAREN,
  [586] = 1,
    ACTIONS(252), 1,
      aux_sym_each_directive_token1,
  [590] = 1,
    ACTIONS(254), 1,
      sym_code,
  [594] = 1,
    ACTIONS(256), 1,
      anon_sym_RBRACE_RBRACE,
  [598] = 1,
    ACTIONS(258), 1,
      sym_code,
  [602] = 1,
    ACTIONS(260), 1,
      anon_sym_RPAREN,
  [606] = 1,
    ACTIONS(262), 1,
      anon_sym_RBRACE_RBRACE,
  [610] = 1,
    ACTIONS(264), 1,
      anon_sym_COMMA,
  [614] = 1,
    ACTIONS(266), 1,
      anon_sym_RBRACE_RBRACE,
  [618] = 1,
    ACTIONS(268), 1,
      sym_code,
  [622] = 1,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
  [626] = 1,
    ACTIONS(272), 1,
      anon_sym_RBRACE_RBRACE,
  [630] = 1,
    ACTIONS(274), 1,
      sym_code,
  [634] = 1,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
  [638] = 1,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
  [642] = 1,
    ACTIONS(280), 1,
      aux_sym_partial_directive_token1,
  [646] = 1,
    ACTIONS(282), 1,
      aux_sym_each_directive_token2,
  [650] = 1,
    ACTIONS(284), 1,
      anon_sym_LPAREN,
  [654] = 1,
    ACTIONS(286), 1,
      anon_sym_COMMA,
  [658] = 1,
    ACTIONS(288), 1,
      aux_sym_each_directive_token1,
  [662] = 1,
    ACTIONS(290), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(21)] = 0,
  [SMALL_STATE(22)] = 14,
  [SMALL_STATE(23)] = 28,
  [SMALL_STATE(24)] = 42,
  [SMALL_STATE(25)] = 56,
  [SMALL_STATE(26)] = 70,
  [SMALL_STATE(27)] = 84,
  [SMALL_STATE(28)] = 98,
  [SMALL_STATE(29)] = 112,
  [SMALL_STATE(30)] = 126,
  [SMALL_STATE(31)] = 140,
  [SMALL_STATE(32)] = 154,
  [SMALL_STATE(33)] = 168,
  [SMALL_STATE(34)] = 182,
  [SMALL_STATE(35)] = 196,
  [SMALL_STATE(36)] = 210,
  [SMALL_STATE(37)] = 222,
  [SMALL_STATE(38)] = 234,
  [SMALL_STATE(39)] = 246,
  [SMALL_STATE(40)] = 258,
  [SMALL_STATE(41)] = 270,
  [SMALL_STATE(42)] = 282,
  [SMALL_STATE(43)] = 294,
  [SMALL_STATE(44)] = 306,
  [SMALL_STATE(45)] = 318,
  [SMALL_STATE(46)] = 330,
  [SMALL_STATE(47)] = 342,
  [SMALL_STATE(48)] = 354,
  [SMALL_STATE(49)] = 366,
  [SMALL_STATE(50)] = 378,
  [SMALL_STATE(51)] = 390,
  [SMALL_STATE(52)] = 401,
  [SMALL_STATE(53)] = 412,
  [SMALL_STATE(54)] = 423,
  [SMALL_STATE(55)] = 434,
  [SMALL_STATE(56)] = 445,
  [SMALL_STATE(57)] = 452,
  [SMALL_STATE(58)] = 459,
  [SMALL_STATE(59)] = 466,
  [SMALL_STATE(60)] = 473,
  [SMALL_STATE(61)] = 480,
  [SMALL_STATE(62)] = 487,
  [SMALL_STATE(63)] = 494,
  [SMALL_STATE(64)] = 501,
  [SMALL_STATE(65)] = 508,
  [SMALL_STATE(66)] = 515,
  [SMALL_STATE(67)] = 522,
  [SMALL_STATE(68)] = 526,
  [SMALL_STATE(69)] = 530,
  [SMALL_STATE(70)] = 534,
  [SMALL_STATE(71)] = 538,
  [SMALL_STATE(72)] = 542,
  [SMALL_STATE(73)] = 546,
  [SMALL_STATE(74)] = 550,
  [SMALL_STATE(75)] = 554,
  [SMALL_STATE(76)] = 558,
  [SMALL_STATE(77)] = 562,
  [SMALL_STATE(78)] = 566,
  [SMALL_STATE(79)] = 570,
  [SMALL_STATE(80)] = 574,
  [SMALL_STATE(81)] = 578,
  [SMALL_STATE(82)] = 582,
  [SMALL_STATE(83)] = 586,
  [SMALL_STATE(84)] = 590,
  [SMALL_STATE(85)] = 594,
  [SMALL_STATE(86)] = 598,
  [SMALL_STATE(87)] = 602,
  [SMALL_STATE(88)] = 606,
  [SMALL_STATE(89)] = 610,
  [SMALL_STATE(90)] = 614,
  [SMALL_STATE(91)] = 618,
  [SMALL_STATE(92)] = 622,
  [SMALL_STATE(93)] = 626,
  [SMALL_STATE(94)] = 630,
  [SMALL_STATE(95)] = 634,
  [SMALL_STATE(96)] = 638,
  [SMALL_STATE(97)] = 642,
  [SMALL_STATE(98)] = 646,
  [SMALL_STATE(99)] = 650,
  [SMALL_STATE(100)] = 654,
  [SMALL_STATE(101)] = 658,
  [SMALL_STATE(102)] = 662,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(6),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(56),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(66),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(65),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(64),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(94),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(102),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(99),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 3, .production_id = 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_directive, 4, .production_id = 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(13),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(58),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(59),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(61),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(62),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(86),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(82),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2), SHIFT_REPEAT(81),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 9),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 10),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 2),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_directive, 2),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_output_directive, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_directive, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_directive, 3, .production_id = 1),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_directive, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 4, .production_id = 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 5, .production_id = 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_directive, 6, .production_id = 2),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_partial_directive, 6, .production_id = 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_each_directive, 8),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_if_directive_repeat1, 2),
  [171] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_if_directive_repeat1, 2), SHIFT_REPEAT(63),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [230] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jqtpl(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
